"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
	if n == 0:
		return 1
	if n == 1:
		return 2
	return fib(n-1) + fib(n-2)


i = 0
ith_fib = 1
result = 0
while ith_fib < 4000000:
	if ith_fib%2 == 0:
		result+=ith_fib
	i+=1
	ith_fib=fib(i)

print result